### PR TITLE
Fixing unbound variable for bash differences + readme update

### PR DESCRIPTION
**Pull request by NorseGaud**
## Description

1. User was seeing `/usr/local/var/buildkite-agent/plugins/github-com-chef-anka-buildkite-plugin-v0-5-0/hooks/command: line 41: pull_args[@]: unbound variable`

2. Readme shows to use a list item to start the plugin name. The same user with the unbound variable and even myself cannot get that to work.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by NorseGaud** [comment]
@tduffield, looks as if the plugin linter doesn't like removing the list/`-` from the readme. 

I've opened a forum post for the issue with buildkite and they told me there is no way it doesn't support lists... Problem is, now other users I talk to (which I told work with) are unable to use lists too: https://forum.buildkite.community/t/no-basic-auth-credentials-yet-using-ecr-plugin/149/12

**Comment by tduffield** [comment]
@NorseGaud it should be a list. if you're running into issues locally you'll want to make sure you're using the latest docker image.

**Comment by tduffield** [comment]
@NorseGaud also, you don't need to manually bump VERSION. We have automation that does that for us!

**Comment by NorseGaud** [comment]
> @NorseGaud also, you don't need to manually bump VERSION. We have automation that does that for us!

Good to know, thanks!

**Pull request merged**
